name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  create-staging-repository:
    name: Create staging repository
    runs-on: ubuntu-latest
    outputs:
      repository_id: ${{ steps.create.outputs.repository_id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@v1.1
        with:
          username: ${{ secrets.OSSRH_USERNAME }}
          password: ${{ secrets.OSSRH_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
          base_url: https://s01.oss.sonatype.org/service/local/
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    needs: create-staging-repository
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Create GPG Key ring
        shell: bash
        run: |
          gpg --batch --pinentry-mode loopback --passphrase $passphrase --export-secret-keys -o ./secring.gpg
        env:
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Make gradlew executable
        if: matrix.platform != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        shell: bash
        run: |
          ./gradlew publish -Pgradle.publish.key=$gradle_publish_key -Pgradle.publish.secret=$gradle_publish_secret -Psigning.keyId=$signing_keyId -Psigning.password=$signing_password -Psigning.secretKeyRingFile=./secring.gpg
        env:
          repoPassword: ${{ secrets.OSSRH_PASSWORD }}
          repoUsername: ${{ secrets.OSSRH_USERNAME }}
          gradle_publish_key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle_publish_secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          signing_keyId: ${{ secrets.SIGNING_KEY_ID }}
          signing_password: ${{ secrets.SIGNING_PASSWORD }}
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
