name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_sonatypeReleaseRepositoryPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeReleaseRepositoryUsername: ${{ secrets.OSSRH_USERNAME }}
