name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Make gradlew executable
        if: matrix.platform != 'windows-latest'
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Publish package
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: publish -PORG_GRADLE_PROJECT_sonatypeReleaseRepositoryPassword=$ORG_GRADLE_PROJECT_sonatypeReleaseRepositoryPassword -PORG_GRADLE_PROJECT_sonatypeReleaseRepositoryUsername=$ORG_GRADLE_PROJECT_sonatypeReleaseRepositoryUsername -Pgradle.publish.key=$gradle_publish_key -Pgradle.publish.secret=$gradle_publish_secret -Psigning.keyId=$signing_keyId -Psigning.password=$signing_password -Psigning.secretKeyRingFile=~/.gnupg/secring.gpg
        env:
          ORG_GRADLE_PROJECT_sonatypeReleaseRepositoryPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeReleaseRepositoryUsername: ${{ secrets.OSSRH_USERNAME }}
          gradle_publish_key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle_publish_secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          signing_keyId: ${{ secrets.SIGNING_KEY_ID }}
          signing_password: ${{ secrets.SIGNING_PASSWORD }}
